### ISSUE TITLE
Can't create user

### ISSUE THREAD

**Issue by obsidienne** [puemos/radiopush#26]
Hi,

One of my user can't connect. Here the error stack

```web.1  | Request: GET /auth/spotify/callback?code=<secret token>
 web.1  | ** (exit) an exception was raised:
 web.1  |     ** (Poison.SyntaxError) Unexpected token at position 0: F
 web.1  |         (poison 3.1.0) lib/poison/parser.ex:57: Poison.Parser.parse!/2
 web.1  |         (poison 3.1.0) lib/poison.ex:83: Poison.decode!/2
 web.1  |         (spotify_ex 2.2.0) lib/spotify/profile.ex:30: Spotify.Profile.handle_response/1
 web.1  |         (radiopush 0.2.1) lib/radiopush/domains/services/spotify/client/spotify_ex_impl.ex:16: Radiopush.Spotify.Client.SpotifyExImpl.run/3
 web.1  |         (radiopush 0.2.1) lib/radiopush/commands/fetch_or_create_user.ex:30: Radiopush.Cmd.FetchOrCreateUser.run/2
 web.1  |         (radiopush 0.2.1) lib/radiopush_web/controllers/user_authentication_controller.ex:1: RadiopushWeb.UserAuthenticationController.action/2
 web.1  |         (radiopush 0.2.1) lib/radiopush/domains/services/spotify/spotify_client_impl.ex:18: Radiopush.Spotify.SpotifyClientImpl.get_profile/1
 web.1  |         (radiopush 0.2.1) lib/radiopush_web/controllers/user_authentication_controller.ex:12: RadiopushWeb.UserAuthenticationController.authenticate/2
```

He's using an android phone.

**Comment by obsidienne** [comment]
when in dev mode, the spotify app must list all account authorized.
